version: "3.8"
services:
    imeiminer:
        build: .
        ports:
        - 8080:8080
        restart: unless-stopped
        environment:
          HOST: 0.0.0.0
          PORT: 8080
          DB_URL: mongodb://root:root@mongodb:27017/
          DB_NAME: moee
          
    mongodb:
        image : mongo:5.0.6-focal
        volumes:
        - /mnt/imeiminer:/data/db
        restart: unless-stopped
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: root
          ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/

            