version: "3.8"
services:
    mongodb:
        image : mongo:5.0.6-focal
        container_name: mongodb
        volumes:
        - /mnt/imeiminer:/data/db
        ports:
        - 27017:27017
        restart: unless-stopped
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: root
          ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/

            